language: julia
os:
  - linux
  - osx
julia:
  - 1.3
  - 1.5
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
  - julia: nightly
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'using Pkg; ps=Pkg.PackageSpec(name="Documenter", version="0.19"); Pkg.add(ps); Pkg.pin(ps); include(joinpath("docs", "make.jl"))'
